<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions name="hello-policy" targetNamespace="http://thomasjohansen.it/hello"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512/">

    <wsp:Policy wsu:Id="SamlPolicy">
        <sp:TransportBinding>
            <wsp:Policy>
                <sp:TransportToken>
                    <wsp:Policy>
                        <sp:HttpsToken>
                            <wsp:Policy>
                                <!--<sp:RequireClientCertificate/>-->
                            </wsp:Policy>
                        </sp:HttpsToken>
                    </wsp:Policy>
                </sp:TransportToken>
                <sp:AlgorithmSuite>
                    <wsp:Policy>
                        <sp:Basic256/>
                    </wsp:Policy>
                </sp:AlgorithmSuite>
                <sp:IncludeTimestamp/>
            </wsp:Policy>
        </sp:TransportBinding>
        <sp:EndorsingSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
            <wsp:Policy>
                <sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                    <sp:RequestSecurityTokenTemplate>
                        <!--<wst:TokenType>urn:oasis:names:tc:SAML:2.0:assertion</wst:TokenType>-->
                        <t:Claims Dialect="http://schemas.xmlsoap.org/ws/2005/05/identity"
                                  xmlns:ic="http://schemas.xmlsoap.org/ws/2005/05/identity">
                            <ic:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                                          Optional="false"/>
                        </t:Claims>
                    </sp:RequestSecurityTokenTemplate>
                    <wsp:Policy>
                        <sp:RequireInternalReference/>
                    </wsp:Policy>
                </sp:IssuedToken>
                <sp:Trust13>
                    <wsp:Policy>
                        <sp:MustSupportIssuedTokens/>
                        <sp:RequireClientEntropy/>
                        <sp:RequireServerEntropy/>
                    </wsp:Policy>
                </sp:Trust13>
            </wsp:Policy>
        </sp:EndorsingSupportingTokens>
    </wsp:Policy>

</wsdl:definitions>